# Generated by Django 3.2 on 2021-04-21 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorder',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.customer')),
            ],
        ),
    ]
