# Generated by Django 3.2 on 2021-04-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_answered',
            field=models.DateTimeField(default=None),
        ),
    ]
