# Generated by Django 3.2 on 2021-04-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_time_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_answered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
