# Generated by Django 3.2 on 2021-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_question_time_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
