# Generated by Django 3.2 on 2021-04-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_question_time_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_answered',
        ),
    ]
