# Generated by Django 3.2 on 2021-04-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_question_time_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='THIS QUESTION HAS NOT BEEN ANSWERED, PLEASE CHECK BACK LATER', max_length=300),
        ),
    ]
