# Generated by Django 3.2 on 2021-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_question_answer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trustedcustomer',
            constraint=models.UniqueConstraint(fields=('username', 'trusted_username'), name='unique trust pair'),
        ),
        migrations.AddConstraint(
            model_name='untrustedcustomer',
            constraint=models.UniqueConstraint(fields=('username', 'untrusted_username'), name='unique untrust pair'),
        ),
    ]
